
# Permalinks
permalink: pretty

# Setup
title: 'Life in White Noise'
tagline: 'Independent work life podcast'
description: 'Two dudes talking about independent work/life and what it means to them.'
url: http://lifeinwhitenoise.com
baseurl: /

author:
  name: 'Dustin Delatore'
  url: 'https://twitter.com/whos_dustin'

paginate: 5

# Custom vars
season: 1

defaults:
- scope:
  path: ''
    type: posts
  values:
    layout: post
    image: ''
    title: ''
    excerpt: ''
    audio: ''
